spring:
  application:
    name: canalysisbackend

  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/canalysis}
    username: canalysis
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none