services:
  db:
    container_name: canalysis-db
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: canalysis
      POSTGRES_DB: canalysis
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U canalysis -d canalysis" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    container_name: canalysis-backend
    build:
      context: ./canalysisbackend
      dockerfile: ./dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DATASOURCE_URL: jdbc:postgresql://db:5432/canalysis
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres-data: